name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate env.js from GitHub Secrets (always overwrite)
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
        run: |
          echo "Luôn ghi đè env.js từ GitHub Secrets..."
          missing=()
          [ -z "${VITE_FIREBASE_API_KEY}" ] && missing+=("VITE_FIREBASE_API_KEY")
          [ -z "${VITE_FIREBASE_APP_ID}" ] && missing+=("VITE_FIREBASE_APP_ID")
          [ -z "${VITE_FIREBASE_AUTH_DOMAIN}" ] && missing+=("VITE_FIREBASE_AUTH_DOMAIN")
          [ -z "${VITE_FIREBASE_MESSAGING_SENDER_ID}" ] && missing+=("VITE_FIREBASE_MESSAGING_SENDER_ID")
          [ -z "${VITE_FIREBASE_PROJECT_ID}" ] && missing+=("VITE_FIREBASE_PROJECT_ID")
          [ -z "${VITE_FIREBASE_STORAGE_BUCKET}" ] && missing+=("VITE_FIREBASE_STORAGE_BUCKET")
          if [ ${#missing[@]} -gt 0 ]; then
            echo "Thiếu GitHub Secrets 1: ${missing[*]}" && exit 1
          fi
          rm -f env.js
          cat > env.js << 'EOF'
          window.env = {
              VITE_FIREBASE_API_KEY: "${{ secrets.VITE_FIREBASE_API_KEY }}",
              VITE_FIREBASE_APP_ID: "${{ secrets.VITE_FIREBASE_APP_ID }}",
              VITE_FIREBASE_AUTH_DOMAIN: "${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}",
              VITE_FIREBASE_MESSAGING_SENDER_ID: "${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}",
              VITE_FIREBASE_PROJECT_ID: "${{ secrets.VITE_FIREBASE_PROJECT_ID }}",
              VITE_FIREBASE_STORAGE_BUCKET: "${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}"
          };
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

